config/routes.rb
Rails.application.routes.draw do
	
	root to: 'surveys#index'
	resources :surveys

	devise_for :users, controllers: {
		sessions: 'users/sessions', 
		confirmations: 'confirmations',
		omniauth_callbacks: 'users/omniauth_callbacks'
	}

	scope "/admin" do
  		resources :users
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :surveys
	mount_uploader :avatar, AvatarUploader
    before_create :set_user_role

    devise :database_authenticatable, :registerable, 
    :recoverable, :rememberable, :validatable, :confirmable,
    :omniauthable, :omniauth_providers => [:facebook]

    def full_name
    	first_name + last_name
    end

    def admin?
    	self.role == "admin"
    end

    def set_user_role
        self.role = "visitor"
    end


    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
                user.email = data["email"] if user.email.blank?
            end
        end
    end

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0,20]
            user.first_name = auth.info.first_name
            user.last_name = auth.info.last_name
            user.avatar = auth.info.image
        end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  #def create
   
   # super do |resource|
    #  BackgroundWorker.trigger(resource)
   # end
  #end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 # before_action :authorize_admin
	
	def index
		@user = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		
		redirect_to users_path
	end

	private

	# def authorize_admin
	# 	redirect_to root_path, alert: 'Access Denied' unless current_user.role=="admin"
		
	# 	if current_user.role == "visitor"
	# 		return
	# 	end
	# end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :role, :email, :password, :password_confirmation, :avatar)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit Users</h2>

<%= form_with(model: @user, local: true) do |f| %>
  
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :Last_Name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :Avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, ['visitor', 'admin'] %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Index Method</h1>
<table>
	<tr>
		<th>ID</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Avatar</th>
		<th>Role</th>
		<th>Email Address</th>
		<th>Edit</th>
		<th>Update</th>
		<th>Show</th>
		<th>Delete</th>
	</tr>

	<% @user.each do |u| %>
	<tr>
		<td><%= u.id %></td>
		<td><%= u.first_name %></td>
		<td><%= u.last_name %></td>
		<td><%= image_tag(u.avatar.url) if u.avatar? %></td>
		<td class="red"><%= u.role %></td>
		<td><%= u.email %></td>
		<td><%= link_to 'Edit', edit_user_path(u) %></td>
		<td><%= link_to 'Update', user_path(u) %></td>
		<td><%= link_to 'show', user_path(u) %></td>
		<td><%= link_to 'Delete', user_path(u), method: :delete, data:{ confirm: 'Are you sure'} %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Create New User', new_user_path %>

app/views/users/new.html.erb
<h2>Create Users</h2>

<%= form_with(model: @user, local: true) do |f| %>

<div class="field">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %>
</div>

<div class="field">
  <%= f.label :Last_Name %><br />
  <%= f.text_field :last_name %>
</div>

<div class="field">
  <%= f.label :Avatar %><br />
  <%= f.file_field :avatar %>
</div>

<div class="field">
  <%= f.label :role %><br />
  <%= f.select :role, ['visitor', 'admin'] %>
</div>

<div class="field">
  <%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
</div>

<div class="field">
  <%= f.label :password %>
  <% if @minimum_password_length %>
  <em>(<%= @minimum_password_length %> characters minimum)</em>
  <% end %><br />
  <%= f.password_field :password, autocomplete: "new-password" %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</div>

<div class="actions">
  <%= f.submit "create" %>
</div>

<% end %>

app/views/users/show.html.erb
<h1>Show User</h1>
<p>
	<strong>First Name</strong>:
	<%= @user.first_name %>
</p>

<p>
	<strong>Last Name</strong>:
	<%= @user.last_name %>
</p>

<p>
	<strong>Avatar</strong>:
	<%= image_tag(@user.avatar.url) %>
</p>
<p>
	<strong>Role</strong>:
	<%= @user.role %>
</p>
<p>
	<strong>Email Address</strong>:
	<%= @user.email %>
</p>

<p>
	<strong>Password</strong>:
	<%= @user.password.inspect %>
</p>

<%= link_to 'Back', users_path %>