config/routes.rb
Rails.application.routes.draw do
	
	root to: 'surveys#index'
	resources :surveys

	devise_for :users, controllers: {
		sessions: 'users/sessions', 
		confirmations: 'confirmations',
		omniauth_callbacks: 'users/omniauth_callbacks'
	}

	scope "/admin" do
  		resources :users
	end

end

app/models/survey.rb
class Survey < ApplicationRecord
	before_create :set_status_pending
	before_save :check_status
	belongs_to :user
	self.per_page = 5


	STATUSES = {
		'pending'     => 'pending',
		'completed'   => 'completed',
		'expired'     => 'expired'
	}

	def self.valid_statuses
		STATUSES.keys
	end

	def set_status_pending
		self.status = "pending"
	end

	def check_status
		if Date.today < self.due_date
			if self.name.present? && self.gender.present? && self.province.present? && self.interest.present? && self.biography.present?
				self.status = 'completed'
			else
				self.status = 'pending'
			end
		else
			self.status = 'expired'
		end
	end


	# validates :status, inclusion: { in: valid_statuses },
	# presence: true

	def extended_status
		STATUSES[status]
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

	 before_action :check_user_is_logged_in?

	def index
		if current_user.role == "admin"
			@surveys = Survey.paginate(page: params[:page])
		else
			@surveys = current_user.surveys
		end
	end

	def new
		@survey = Survey.new
	end

	def create
		@survey = Survey.new(params_survey)
		# @survey.user = current_user
		
		if @survey.save!
			redirect_to @survey
		else
			render 'new'
		end
	end

	def show
		@survey = Survey.find(params[:id])
	end

	def edit
		@survey = Survey.find(params[:id])
	end

	def update
		@survey = Survey.find(params[:id])
		if  status == "expired"
			redirect_to surveys_path, error: "after expired user can't edit form"
		else
			if @survey.update(params_survey)
				redirect_to @survey
			else
				render 'new'
			end
		end
	end

	def destroy
		@survey = Survey.find(params[:id])
		@survey.destroy

		redirect_to surveys_path
	end

	private
	def check_user_is_logged_in?
		authenticate_user! if current_user.nil?
	end

	def params_survey
		params.require(:survey).permit(:name, :biography, :gender, :province, :status, :due_date, :user_id, :interest =>[])
	end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_with(model: @survey, local: true) do |form| %>

<% if current_user.role == "admin" %>

<p>
	<%= form.label :due_date %><br>
	<%= form.date_select :due_date %>
</p>

<p>
	<%= form.label :Assign_user %>:    
	<%= form.select :user_id, options_from_collection_for_select(User.all, "id", "first_name") %>
</p>

<% else %>

<p>
	<%= form.label :name %>:
	<%= form.text_field :name %>
</p>

<p>
	<%= form.label :gender %>:

	<%= form.radio_button :gender, 'Male' %>
	<%= form.label :gender, 'Male' %>

	<%= form.radio_button :gender, 'Female' %>
	<%= form.label :gender, 'Female' %>
</p>

<p>
	<%= form.label :province %>:
	<%= form.select :province, ['select','Punjab', 'Sindh', 'Balochistan', 'Khyber Pakhtunkhwa'] %>
</p>

<p>
	<%= form.label :interest %>:

	<%= form.check_box :interest, {:multiple => true}, 'Music', nil %>
	<%= form.label :Music %>
	<%= form.check_box :interest, {:multiple => true}, 'Art', nil %>
	<%= form.label :Art %>
	<%= form.check_box :interest, {:multiple => true}, 'Religion', nil %>
	<%= form.label :Religion %>
	<%= form.check_box :interest, {:multiple => true}, 'Movies', nil %>
	<%= form.label :Movies %>
	<%= form.check_box :interest, {:multiple => true}, 'Politics', nil %>
	<%= form.label :Politics %>
	<%= form.check_box :interest, {:multiple => true}, 'Science', nil %>
	<%= form.label :Science %>
	<%= form.check_box :interest, {:multiple => true}, 'Math', nil %>
	<%= form.label :Math %>
</p>

<p>
	<%= form.label :biography %>:
	<%= form.text_area :biography %>
</p>
<%end%>

<p>
	<%= form.submit ({:class => 'btn btn-primary'}) %>
</p>

<%end%>

app/views/surveys/edit.html.erb
<%= render 'form' %>

app/views/surveys/index.html.erb
<h1> Index Page</h1>
<h3 style= "font-style: italic; color: red;"><%= error %></h3>
<table>
	<tr>
		<!-- <th>Created by</th> -->
		<th>User ID</th>
		<th>Name</th>
		<th>Gender</th>
		<th>Province</th>
		<th>Interest</th>
		<th>Biography</th>
		<th>Due_date</th>
		<th>Status</th>
	</tr>


	<% @surveys.each do |survey|%>
	<tr>
		<td><%= survey.id %>
		<!-- <td><%#= survey.user.full_name %></td> -->
		<td><%= survey.name %></td>
		<td><%= survey.gender %></td>
		<td><%= survey.province %></td>
		<td><%= survey.interest %></td>
		<td><%= survey.biography %></td>
		<td><%= survey.due_date %></td>
		<td><%= survey.status %></td>
		<td><%= link_to 'Edit', edit_survey_path(survey) %></td>
		<td><%= link_to 'Update', survey_path(survey) %></td>
		<td><%= link_to 'Delete', survey_path(survey),
		method: :delete,
		data: {confirm: 'Are you mad?'} %></td>					  
	</tr>
	<%end%>
</table>

<%= link_to 'New Form', new_survey_path %><br>
<%= link_to 'Logout', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}  %><br>
<%= link_to 'New sign_up only for admin', new_user_path %><br>


<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @surveys %>
    </div>
    <%= will_paginate @surveys, :container => false %>
</div>

app/views/surveys/new.html.erb
<h1>New method</h1>

<%= render 'form' %>

app/views/surveys/show.html.erb
<h1>Show method</h1>

<p>
	<strong>Name:</strong>
	<%= @survey.name %>
</p>
<p>
	<strong>Status:</strong>
	<%= @survey.status %>
</p>

<p>
	<strong>Due Date:</strong>
	<%= @survey.due_date %>
</p>
<p>
	<strong>Gender:</strong>
	<%= @survey.gender %>
</p>
<p>
	<strong>Province:</strong>
	<%= @survey.province %>
</p>
<p>
	<strong>Interest:</strong>
	<%= @survey.interest %>
</p>
<p>
	<strong>Biography:</strong>
	<%= @survey.biography %>
</p>

<%= link_to 'Click for Edit this form', edit_survey_path(@survey) %><br>
<%= link_to 'Click to go back', surveys_path %>